app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('category/', include('categorygame.urls', namespace='category')),
    path('user/', include('user.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorygame/urls.py
from django.contrib import admin
from django.urls import path
from categorygame.views import *

app_name = 'category'

urlpatterns = [
    path('<slug:category_slug>/', category, name='index'),
    path('<slug:category_slug>/<slug:buld_slug>/', buld, name='buld'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import  *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('newbuld/', newbuld, name='newbuld'),
    path('new/', new, name='new'),
    path('forum/', forum, name='forum'),
    path('rmtgame/', rmtgame, name='rmtgame'),
]

user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

categorygame/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Название игры')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    
    class Meta:
        db_table = 'category'
    
    def __str__(self):
        return self.name

class Buld(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Название игры')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='categorygame_imgas',blank=True, null=True, verbose_name='Изображение')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'buld'
    
    def __str__(self):
        return self.name
    

main/models.py
from django.db import models


user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True, verbose_name='аватарка пользователя')
    username = models.CharField(max_length=150, unique=True ,verbose_name='имя пользователя')
     
    
    class Meta:
        db_table = 'user'
    
    def __str__(self):
        return self.username

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from user.models import User

class UserLoginForm(AuthenticationForm):

    username =  forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 
                  'password',
                  ]


class UserRegistrationForm(UserCreationForm):

    username =  forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = [
            'username', 
            'email',
            'password1',
            'password2',
            ]

class ProfileForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = [
            "image",
            'username', 
            ]
        
        widgets = {

            'image': forms.FileInput(attrs= {'class':'avatar_form_label', 'required': False,}),
            'username': forms.TextInput(attrs= {'class':'nikname_form_input'}),

        }
        

categorygame/views.py
from django.shortcuts import render
from categorygame.models import *


def category(request, category_slug):

    category = Category.objects.get(slug=category_slug)

    buldy = Buld.objects.filter(category__slug=category_slug)
    
    context = {
        'buldy': buldy,
        'category': category,
            
    }
    
    return render(request, 'category.html', context)

def buld(request, category_slug, buld_slug):

    category = Category.objects.get(slug=category_slug)

    buldys = Buld.objects.get(category__slug=category_slug, slug=buld_slug)

    context = {
        'title': 'BuldMMO | |',
        'buldys': buldys,
        'category': category,
    }

    return render(request, 'buld.html', context)


main/views.py
from django.http import HttpResponse
from django.shortcuts import render

from categorygame.models import *

def index(request):
   
    context = {
      'title': 'BuldMMO',
    }

    return render(request, 'index.html', context)

def newbuld(request):
    context = {
        'title': 'BuldMMO | Свежие билды',
    }
    return render(request, 'newbuld.html', context)

def new(request):
    context = {
        'title': 'BuldMMO | Новости',
    }
    return render(request, 'new.html', context)

def forum(request):
    context = {
        'title': 'BuldMMO | Форум',
        'content': 'В разработке...',
    }
    return render(request, 'forum.html', context)

def rmtgame(request):
    context = {
        'title': 'BuldMMO | Рмт информация',
    }
    return render(request, 'rmtgame.html', context)



user/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from user.forms import *

def login(request):

    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    
    else:
        form = UserLoginForm()

    context = {
        'title': 'BuldMMO | Вход',
        'form': form,
    }

    return render(request, 'user/login.html', context)

def registration(request):

    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
    
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'BuldMMO | Регистрация',
        'form': form,
    }

    return render(request, 'user/registration.html', context)

@login_required
def profile(request):

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
    
    else:
        form = ProfileForm( instance=request.user )

    context = {
        'form': form,
    }

    return render(request, 'user/profile.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))

categorygame/templates/buld.html
{% extends "base.html" %}
{% load static %}

{% block title %} BuldMMO | {{ category.name }} | {{buldys.name}} {% endblock%}

{% block header %}
<div class="header">
    <div class="header_logo">
        <a href="/">BuldMMO</a>
    </div>
    
    <div class="header_menu">
    </div> 

    <div class="header_search">
    </div>  
    {% if request.user.is_authenticated %}
            <div class="header_profile">
                <ul class="menu_profile">
                    <li>
                        <button>
                            <div class="icon_profile">
                                {% if user.avatar.url %}
                                    <img src="{{ user.avatar.url }}" alt="avatar">
                                {% else %}
                                    <img src="{% static "img\iconavatar.png" %}" alt="avatar">
                                {% endif %}
                            </div>
                        </button>
                        <ul class="submenu_profile">
                        
                            <li><a href="{% url "user:profile" %}">profile</a></li>
                            <li><a href="{% url "user:logout" %}">logout</a></li>
                            {% if user.is_superuser %}
                            <li><a href="{% url "admin:index" %}">admin</a></li>
                            {% endif %}
        
                        </ul>
                    </li>
                </ul>
            </div>
            {% else %}
                <div class="header_login">
                    <a href="#">Login</a>
                    <p> | </p>
                    <a href="#">Register</a>
                </div>  
            {% endif %}
</div>
{% endblock header %}

{% block content %}
<div class="content">
    <div class="left_content_block">
    </div>

    <div class="center_content_block">
        <div class="display_block-s">
        </div>
        <div class="content_block">
            <p> {{buldys.name}}</p>
            {% if  buldys.image %}
            <div class="img_content_block">
                <img src="{{ buldys.image.url }}"/>
            </div>
            {% endif %}
            <p class="description_content_block-2"> {{ buldys.description}}</p>
        </div>                 

    </div>

    <div class="right_content_block">
    </div>
</div>
{% endblock content %}

categorygame/templates/category.html
{% extends "base.html" %}
{% load static %}
{% load apps_tags %}

{% block title %} BuldMMO | {{ category.name }} {% endblock%}

{% block content %}
<div class="content">
    <div class="left_content_block">
    </div>

    <div class="center_content_block">
        <div class="display_block-s">
        </div>
        {% for buldes in buldy %}
        <div class="content_block">
            <a href="{{buldes.slug}}" name="title">{{buldes.name}}
                <div class="img_content_block">
                    {% if buldes.image %}
                    <img src="{{buldes.image.url}}"/>
                    {% endif %}
                </div>
            </a>
            <p class="description_content_block"> {{buldes.description}}</p>
        </div>
        {% endfor %}                    

    </div>

    <div class="right_content_block">
    </div>
</div>
{% endblock content %}

main/templates/forum.html
{% extends "base.html" %}
{% load static %}

{% block bottomenu %}{% endblock bottomenu%}

{% block content %}
<h1 class="wait">{{content}}</h1>
{% endblock content %}

main/templates/index.html
{% extends "base.html" %}
{% load static %}


main/templates/new.html
{% extends "base.html" %}
{% load static %}


{% block bottomenu %}{% endblock bottomenu %}

main/templates/newbuld.html
{% extends "base.html" %}
{% load static %}


main/templates/rmtgame.html
{% extends "base.html" %}
{% load static %}

templates/base.html
{% load static %}
{% load apps_tags %}


<html>
    <head>
        <meta charset="utf-8">
        <title> {% block title %} {{title}} {% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/rem.css' %}">
    </head>
    <body>
    
        {% block header %}
        <div class="header">
            <div class="header_logo">
                <a href="/">BuldMMO</a>
            </div>
            <div class="header_menu">

                <div class="top_menu">
                        <a href="{% url "main:newbuld" %}" class="link_top_menu">Новые билды</a>
                        <a href="{% url "main:new" %}" class="link_top_menu">Новости</a>
                        <a href="{% url "main:forum" %}">Форум</a>
                        <a href="{% url "main:rmtgame" %}" class="link_top_menu">РМТ</a>
                </div> 
                {% block bottomenu %}
                <div class="bottom_menu">
                    
                    <div class="left_menu">
                        {% tag_categoris as category %}
                        {% for categoris in category %}
                            <a href="{% url "category:index" categoris.slug %}">{{categoris.name}}</a>
                        {% endfor %}
                    </div> 
                     
                    <div class="rigth_menu">
                        
                        <ul class="menu">
                            <li>
                                <button></button>
                                <ul class="submenu">
                
                                    <li>
                                        {% tag_categoris as category %}
                                        {% for categoris in category %}
                                            <a href="{% url "category:index" categoris.slug %}">{{categoris.name}}</a>
                                        {% endfor %}
                                    </li>
                
                                </ul>
                            </li>
                        </ul>
                
                    </div> 
                
                </div> 
                {% endblock bottomenu %}

            </div>  

            <div class="header_search">
            </div>  
            
            {% block ligon %}
            {% if request.user.is_authenticated %}
            <div class="header_profile">
                <ul class="menu_profile">
                    <li>
                        <button>
                            <div class="icon_profile">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}">
                                {% else %}
                                    <img src="{% static "img\iconavatar.png" %}">
                                {% endif %}
                            </div>
                        </button>
                        <ul class="submenu_profile">
                        
                            <li><a href="{% url "user:profile" %}">profile</a></li>
                            {% if user.is_superuser %}
                            <li><a href="{% url "admin:index" %}">admin</a></li>
                            {% endif %}
                            <li><a href="{% url "user:logout" %}">logout</a></li>

                        </ul>
                    </li>
                </ul>
            </div>
            {% else %}
                <div class="header_login">
                    <a href="{% url "user:login" %}">Login</a>
                    <p> | </p>
                    <a href="{% url "user:registration" %}">Register</a>
                </div>  
            {% endif %}
              
            {% endblock ligon %}
            
        </div>
        {% endblock header %}

        {% block content %}

        {% endblock content %}

        {% include "includes/notifications.html" %}
    </body>
</html>

templates/includes/notifications.html
{% load static %}
{% if form.non_field_errors %}
   <div class="container_erores">
       <div class="block_erores">
           <div class="block_erores_content">
            {{form.non_field_errors}}
           </div>
       </div>
   </div>
{% endif %}

user/templates/user/login.html
{% extends "base.html" %}

{% block header %}

<div class="header">
    <div class="header_logo">
        <a href="/">BuldMMO</a>
    </div>
</div>
    
{% endblock header %}

{% block content %}

<div class="content">
    <div class="left_content_profile"></div>
    <div class="center_content_profile">
        <div class="login_block">
            
            <form action="{% url 'user:login' %}" method="post">

                <div id="logins_btn" class="forum-login">
                    <h1>Войти</h1>
                    {% csrf_token %}

                    <p>
                        <label for="username" class="form_label" data-icon="u" > Ваш никнайм </label>
                        <input id="username" name="username" class="form_input" value="{% if form.username.value %}{{form.username.value}}{% endif %}" required="required" type="text" placeholder=""/>
                    </p>
                    <p>
                        <label for="password" class="form_label" data-icon="p"> Ваш пароль </label>
                        <input id="password" name="password" class="form_input" required="required" type="password" placeholder="" />
                    </p>

                    <p class="login_btn">
                        <button type='submit'>Войти</button>
                        <div class="fr2">
                            <a href="/">Назад</a>
                            <p>|</p>
                            <a href="{% url "user:registration" %}">Нет аккаунта?</a>
                        </div>
                    </p> 

                </div>
    
            </form>
        </div>
    </div>
    <div class="rigth_content_profile"></div>
</div>
{% endblock content %}

user/templates/user/logout.html
{% extends "base.html" %}

user/templates/user/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
BuldMMO | {{user.username}} | Профиль
{% endblock title %}

{% block header %} 
<div class="header">
    <div class="header_logo">
        <a href="/">BuldMMO</a>
    </div>
    <div class="header_menu"></div>
    <div class="header_search"></div>
    <div class="header_profile">
        <ul class="menu_profile">
        </ul>
    </div>
</div>
{% endblock header %}

{% block content %}
    <div class="content_profile">
    <div class="left_content_profile"></div>
    <div class="center_content_profile">
        <div class="profile_block">
            <div class="left_block_profile">
                <div class="top_left_block_profile">
                    <div class="avatar_profile">
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="avatar">
                        {% else %}
                            <img src="{% static "img\iconavatar.png" %}" alt="avatar">
                        {% endif %}
                    </div>
                    <div class="name_profile">
                        <p>{{user.username}}</p>
                        <div class="icon_copy_menu"></div>
                    </div>
                </div>
                <div class="bottom_left_block_profile">
                    <div class="bottom_left_menu_profile">
                        <div class="top_bottom_left_menu_profile">

                            <div class="menu_profile">
                                <div class="tab">
                                    <a href="#tab_1" class="tab_a">Профиль</a>
                                    <img src="{% static "img\home.png" %}" alt="">
                                </div>
                                <div class="tab">
                                    <a href="#tab_2" class="tab_a">Безопасность </a>
                                    <img src="{% static "img\settings.png" %}" alt="">
                                </div>
                            </div>
                
                        </div>

                        <div class="bottom_bottom_left_menu_profile">

                            <li><a href="/"><- Назад </a></li>
                            <p>|</p>
                            <li><a href="{% url "user:logout" %}">> Выйти <</a></li>
                            {% if user.is_superuser %}
                            <p>|</p>
                            <li><a href="{% url "admin:index" %}">admin</a></li>
                            {% endif %}
                        
                        </div>
                    </div>
                </div>
            </div>
            <div class="rigth_block_profile">
                <div class="top_rigth_block_profile">
                    <div class="img"></div>
                </div>
                <div class="bottom_rigth_block_profile">

                    <div id="tab_2" class="tab_display">
                        <div class="left_bottom_rigth_block_prfile">
                            <p style="color: wheat; font-family: monospace; font-size: 100px;"> Пока что нечего тута, нету.</p>
                        </div>
                    </div>

                    <div id="tab_1" class="tab_display">
                        <div class="left_bottom_rigth_block_prfile">
                            <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data" >
                                {% csrf_token %}
                                <div>
                                    <p class="mt-p">
                                        <label for="{{ form.image.id_for_label }}" class="avatar_form_label"> <img src="{% static "img\open.png" %}" alt=""> Сменить аватарку </label>
                                        {{ form.image}}
                                    </p>
                                    <p class="mt-p">
                                        <label class="gh-1">Смена ника </label>
                                        <p class="mt-p-2">
                                            <label for="{{ form.username.id_for_label }}" class="nikname_form_label"><img src="{% static "img\pen.png" %}" alt=""> Смена ника </label>
                                            {{ form.username }}
                                        </p>
                                    </p>

                                    <p class="login_btn">
                                        <button type='submit' formmethod="post">Сохранить</button>
                                    </p> 
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
                <div class="footer_rigth_block_profile">
                    <p>BuldMMO  приветствует тебя {{user.username}}. Был создан ради первого проекта Zarfiks ом.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="rigth_content_profile"></div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% endblock content %}

user/templates/user/registration.html
{% extends "base.html" %}

{% block header %}

<div class="header">
    <div class="header_logo">
        <a href="/">BuldMMO</a>
    </div>
</div>
    
{% endblock header %}

{% block content %}

<div class="content">
    <div class="left_content_profile"></div>
    <div class="center_content_profile">
        <div class="login_block">
            
            <form action="{% url 'user:registration' %}" method="post">

                <div id="logins_btn" class="forum-login">
                    <h1>Регистрация</h1>
                    {% csrf_token %}

                    <p>
                        <label for="id_username" class="form_label" data-icon="u" > Username </label>
                        <input id="id_username" name="username" value="{% if form.username.value %}{{form.username.value}}{% endif %}" class="form_input" required="required" type="text" placeholder=""/>
                        {% if form.username.errors %}
                          <div class="errors_block_register">{{form.username.errors}}</div>
                        {% endif %}
                    </p>
                    <p>
                        <label for="id_email" class="form_label" data-icon="p"> Your email </label>
                        <input id="id_email" name="email" value="{% if form.email.value %}{{form.email.value}}{% endif %}" class="form_input" required="required" type="email" placeholder="" />
                        {% if form.email.errors %}
                          <div class="errors_block_register">{{form.email.errors}}</div>
                        {% endif %}
                    </p>
                    <p>
                        <label for="id_password1" class="form_label" data-icon="p"> password </label>
                        <input id="id_password1"  name="password1"  value="{% if form.password1.value %}{{form.password1.value}}{% endif %}" class="form_input" required="required" type="password" placeholder="" />
                        {% if form.password1.errors %}
                          <div class="errors_block_register">{{form.password1.errors}}</div>
                        {% endif %}
                    </p>
                    <p>
                        <label for="id_password2" class="form_label" data-icon="p"> Your password </label>
                        <input id="id_password2" name="password2"  value="{% if form.password2.value %}{{form.password2.value}}{% endif %}" class="form_input" required="required" type="password" placeholder="" />
                        {% if form.password2.errors %}
                          <div class="errors_block_register">{{form.password2.errors}}</div>
                        {% endif %}
                    </p>

                    <p class="login_btn">
                        <button type='submit'>Зарегистрироваться</button>
                        <div class="fr2">
                            <a href="/">Назад</a>
                            <p>|</p>
                            <a href="{% url "user:login" %}">Есть аккаунт?</a>
                        </div>
                    </p> 

                </div>
    
            </form>
        </div>
    </div>
    <div class="rigth_content_profile"></div>
</div>
{% endblock content %}